development: &development
  database_url: <%= ENV['DATABASE_URL'] || 'postgres://postgres@localhost:5432/toshi_development' %>
  log_level: <%= ENV['LOG_LEVEL'] || 'debug' %>
  max_peers: 8
  network: <%= ENV['TOSHI_NETWORK'] || 'testnet3' %>
  peers: []
  redis_url: <%= ENV['REDIS_URL'] || 'redis://127.0.0.1:6379' %>

test:
  <<: *development
  database_url: <%= ENV['DATABASE_URL'] || 'postgres://postgres@localhost:5432/toshi_test' %>
  max_peers: 1

staging:
  database_url: postgres://postgres@127.0.0.1:5432/toshi_staging
  log_level: 'info'
  max_peers: 8
  network: <%= ENV['TOSHI_NETWORK'] || 'bitcoin' %>
  peers: <%= ENV['TOSHI_PEERS'].to_s.split(';') %>

production:
  database_url: <%= ENV['DATABASE_URL'] %>
  log_level: <%= ENV['LOG_LEVEL'] || 'info' %>
  max_peers: 8
  network: <%= ENV['TOSHI_NETWORK'] || 'bitcoin' %>
  peers: <%= ENV['TOSHI_PEERS'].to_s.split(';') %>
  redis_url: <%= ENV['REDIS_URL'] || ENV['REDISTOGO_URL'] || ENV['OPENREDIS_URL'] %>
